class BaseConfig(object):
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = "sqlite:///cyberplot.db"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = "secret"
    API_ATTRIBUTE_VALUE_PREVIEW_LENGTH = 3
    ATTRIBUTE_CLASSIFICATION_CATEGORY_MAX_UNIQUE_COUNT = 10
    HEADSET_SETUP_KEY_LENGTH = 5
    HEADSET_CONNECTOR_MINUTES_TILL_REMOVE_UNUSED = 30