DROP TABLE IF EXISTS Statistics;
DROP TABLE IF EXISTS DatasetVersion;
DROP TABLE IF EXISTS Connector;
DROP TABLE IF EXISTS Attribute;
DROP TABLE IF EXISTS Space;
DROP TABLE IF EXISTS Dataset;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    UID INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(30) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    email VARCHAR(60) UNIQUE NOT NULL,
    accountType TINYINT NOT NULL
);

CREATE TABLE Dataset (
    DID INTEGER NOT NULL,
    UID INTEGER NOT NULL REFERENCES Users(UID),
    name VARCHAR(100) NOT NULL,
    lastEdit DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    spaceDependencies INTEGER NOT NULL DEFAULT 0,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (DID, UID)
);

CREATE TABLE Space (
    SID INTEGER NOT NULL,
    DID INTEGER NOT NULL,
    datasetUID INTEGER NOT NULL,
    ownerUID INTEGER NOT NULL REFERENCES Users(UID),
    name VARCHAR(100) NOT NULL,
    filename TEXT NOT NULL,
    FOREIGN KEY (DID, datasetUID) REFERENCES Dataset(DID, UID),
    PRIMARY KEY (SID, DID, datasetUID, ownerUID)
);

CREATE TABLE Attribute (
    AID INTEGER NOT NULL,
    DID INTEGER NOT NULL,
    UID INTEGER NOT NULL,
    type TINYINT NOT NULL,
    typeMask BINARY NOT NULL,
    missingValueSetting TINYINT NOT NULL DEFAULT 0,
    FOREIGN KEY (DID, UID) REFERENCES Dataset(DID, UID),
    PRIMARY KEY (AID, DID, UID)
);

CREATE TABLE Connector (
    DID INTEGER NOT NULL,
    UID INTEGER NOT NULL,
    type TINYINT NOT NULL,
    key TEXT,
    FOREIGN KEY (DID, UID) REFERENCES Dataset(DID, UID),
    PRIMARY KEY (DID, UID)
);

CREATE TABLE DatasetVersion (
    VID INTEGER NOT NULL,
    DID INTEGER NOT NULL,
    UID INTEGER NOT NULL,
    filename TEXT NOT NULL,
    uploadDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    itemCount INT NOT NULL,
    FOREIGN KEY (DID, UID) REFERENCES Dataset(DID, UID),
    PRIMARY KEY (VID, DID, UID)
);

CREATE TABLE Statistics (
    AID INTEGER NOT NULL,
    DID INTEGER NOT NULL,
    UID INTEGER NOT NULL,
    min FLOAT,
    '1Q' FLOAT,
    med FLOAT,
    '3Q' FLOAT,
    max FLOAT,
    mean FLOAT,
    sdev FLOAT,
    FOREIGN KEY (DID, UID) REFERENCES Dataset(DID, UID),
    PRIMARY KEY (AID, DID, UID)
);